on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

name: release-libs
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.interrogate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: interrogate
        uses: actions/github-script@v6
        with:
          debug: true
          result-encoding: string
          github-token: ${{secrets.GITHUB_TOKEN}}
          retries: 1
          script: |
            const script = require('./scripts/changeFinder.js');
            return await script({github, context, core});
      - run: echo "matrix=${{steps.interrogate.outputs.result}}" >> $GITHUB_OUTPUT
  release-pr:
    runs-on: ubuntu-latest
    needs:
      - changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.matrix)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          path: libs/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.package }}
          monorepo-tags: true
          command: release-pr
