on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

name: release-libs
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.nodePaths }}
    steps:
      - uses: actions/checkout@v3
      - id: interrogate
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          retries: 1
          script: |
            const {execSync} = require('child_process');
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            try {
              const latestRelease = await github.rest.repos.getLatestRelease({
                owner,
                repo
              });
              console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
            } catch(e) {
              console.log('fails get latest release');
            }
            try {
              execSync('git pull --tags');
              execSync(`git reset --hard ${latestRelease.data.tag_name}`);
            } catch(e) {
              console.log('fails remove last release tag')
            }
            const status = execSync(`git diff --name-only origin/staging`, { encoding: 'utf-8'});
            console.log(status);
            const changes = status.split('\n');
            let nodePaths = new Set();
            for (const change of changes) {
              if (change.startsWith('libs/')) {
                  const library = change.split('/')[1];
                  nodePaths.add(library);
              };
            }
            nodePaths = Array.from(nodePaths);
            echo "nodePaths=JSON.stringify(nodePaths)" >> "$GITHUB_ENV"
  release-pr:
    runs-on: ubuntu-latest
    needs:
      - changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(jobs.changeFinder.steps.interrogate.env.nodePaths)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          path: libs/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.package }}
          monorepo-tags: true
          command: release-pr
          
